apiVersion: argoproj.io/v1aplha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoUrl: https://github.com/isubuz/argocd-helm-monorepo-appsets.git
        revision: HEAD
        files:
          - path: "envs/dev/*.yaml"
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .svcName }}'
      labels:
        name: helm-guestbook
    spec:
      project: dev
      source:
        repoURL: https://github.com/isubuz/argocd-helm-monorepo.git
        targetRevision: HEAD
        path: chart
        helm:
          valueFiles:
            - "helm-values/{{ .path.basename }}/{{ .svcName }}/values.yaml"
      syncPolicy:
        automated:
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: "{{ .path.basename }}"
        server: https://kubernetes.default.svc
