apiVersion: argoproj.io/v1aplha1
kind: ApplicationSet
metadata:
  name: qa
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoUrl: https://github.com/isubuz/argocd-helm-monorepo-appsets.git
        revision: c925575244685c300111f69f94e6e2d8aa14769d
        files:
          - path: "envs/qa/gb-1.yaml"
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .svcName }}'
      labels:
        name: helm-guestbook
    spec:
      project: qa
      source:
        repoURL: https://github.com/isubuz/argocd-helm-monorepo.git
        targetRevision: HEAD
        path: chart
        helm:
          valueFiles:
            - "../helm-values/{{ .path.basename }}/{{ .svcName }}.yaml"
      syncPolicy:
        automated:
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: "{{ .path.basename }}"
        server: https://kubernetes.default.svc
